### ISSUE TITLE
Bottom Bar should push the side-bar upwards when open. Or at least its tab header should match the content position

### ISSUE THREAD

**Issue by KrishnaPG** [caplin/FlexLayout#112]
When the sidebars open, the bottom bar tabs and its content do not match, which is very confusing the users.

Please refer to the screenshot below to understand what I mean:

![image](https://user-images.githubusercontent.com/4610831/87305653-79c2c400-c534-11ea-8e7a-750e47069768.png)

For example, in the demo default layout, when you open the `Navigation` sidebar, and then open the bottom bar tabs `Activity Blotter` or `Execution Blotter`, you would see the content gets opened at an offset towards right. 

When someone is presented with an UI like the below in an app, they are more likely to associate the bottom tabs to the area immediately above it, rather than somewhat next to it.

![image](https://user-images.githubusercontent.com/4610831/87305952-ec33a400-c534-11ea-820a-853049e82970.png)

## Suggested Fix
There are few options:

1. When the bottom bar opens, please shift the right sidebar (and left sidebar) also upwards. The complete bottom area belongs to the bottom bar. Anything above it will be divided into, `left` - `center` - `right`.
2. The other option for the bottom bar would be to "overlay" on top of the sidebars and main content (like `z-index` top) when it is open.
3. Final option would be to shift the whole bottom bar to the right when the left sidebar is open. (And shrink its length on the right hand side when the right side bar is open). This way, the `left` and `right` sidebars take priority when then are open and the `bottom` bar just uses the remaining available space, dividing it into `top` content area and the `bottom bar` itself.

Essentially, you would have decide the priority between sidebars and the bottombar. When one is open the other has to shrink in its height or width, based on the priority. Or use different `z-index` to overlay the bars.

Leaving the tab headers dangling to the left, while opening its content to the right is not giving the right user-experience. Tab Headers and the content should be of same size.

**Comment by nealus** [comment]
If you define the bottom border first then it will render first and always show across the full width

**Comment by KrishnaPG** [comment]
@nealus Perfect. Thank you.
