### ISSUE TITLE
Remove module level reference to window, document, navigator

### ISSUE THREAD

**Issue by slonoed** [caplin/FlexLayout#115]
ReactJS if often used in server environment for server side rendering.
In this environment browser globals are not available.

Few modules of FlexLayout use them. Example:
https://github.com/caplin/FlexLayout/blob/bb6c59c964dda883d1b18a7085b373c17b995f44/src/view/Layout.tsx#L55

When this module is imported in NodeJS environment this code will throw an error.
This bug could be checking variables' existence before use.

**Comment by nealus** [comment]
can you create a PR for the required changes please

**Comment by slonoed** [comment]
Hello @nealus !
I will work on PR

**Comment by nealus** [comment]
Thanks for the PR, which I have now merged

**Comment by slonoed** [comment]
@nealus could you publish it to npm? 
Thanks!
