### ISSUE TITLE
React Leaflet Map is displayed in any other TAB popout

### ISSUE THREAD

**Issue by PatrickIl** [caplin/FlexLayout#117]
Hi,
I'm experimenting with FlexLaout. I has created a simple experimental app. I am using the original default layout. In one of the TAB, I'm using react-leaflet to display OpenStreetMap, in another TAB, I'm displaying a Data Grid with some data (but this is not relevant). 
Now the problem I'm struggling with is if I popout the MAP Tab, everything is fine, I see only the MAP with the popout window. But, hoping out any other TAB, displays the content of that TAB, but with the MAP as an overlay. 
Any hint, what do I need to check to prevent this?
I have attached the image of the normal main window, and another depicting the problem. I have also attached a zip of my React Javascript project, which you can run from the client folder, first npm install then  **npm run dev**.

![mainwindow](https://user-images.githubusercontent.com/28356287/88062309-ab401e80-cb36-11ea-9a88-78c3c822d05a.png)
![problem](https://user-images.githubusercontent.com/28356287/88062363-bc892b00-cb36-11ea-951d-3fdae44b7adc.png)

[sandbox.zip](https://github.com/caplin/FlexLayout/files/4954182/sandbox.zip)

**.

**Comment by nealus** [comment]
looks like http://localhost:1234/popout.html is loading the full page (the flexlayout again) rather than the simple container page, in the dev tools I can see: popout.html defined as:
<head>
<link rel="stylesheet" href="/src.e31bb0bc.css"></head>
<body>
    <div id="root"></div>
    <script src="/src.e31bb0bc.js"></script>
</body>

**Comment by PatrickIl** [comment]
The html file you described above is my index.html. I have a popout.html file, copied from Flexlayout examples/demo folder into the same folder as my main page, but it looks like it is not being used, even removing it does not change anything. Is there a special setting that I'm missing?
Thanks a lot, for your help.

**Comment by nealus** [comment]
adding popout.html to the dist dir fixes that problem, but then the popouts are not sizing the content correctly, that may be css?

**Comment by PatrickIl** [comment]
I tried adding the popout.html into the list folder, but it did not work. Is that the way to do it?
Thanks

**Comment by nealus** [comment]
with the popout.html in the dist folder it is being used, the grid is popping out correctly (but css needs changing to fill container element), but the map does not show correctly, maybe because it uses the global window/document rather than the ones for the popout, if that's the case you will have to look at the API and see if you can force it to use the popout windows window/document.

**Comment by nealus** [comment]
actually adding:
```
.leaflet-container {
    width: 100vw !important;
    height: 100vh !important;
}
```
to the <style> in the popout.html fixes the map sizing issue, but the drag does not work (due almost certainly to the use of the global window/document) ( the +/- zoom does work!)

**Comment by PatrickIl** [comment]
Thanks a million, for your help, very appreciated !!!!
