### ISSUE TITLE
More custom icons?

### ISSUE THREAD

**Issue by edemaine** [caplin/FlexLayout#130]
`closeIcon` provides a nice way to customize the close icon, but there doesn't seem to be a similar feature for the other buttons, e.g., minimize/maximize.  (I originally thought that this was what `iconFactory` was for, but now I understand that's for tab icons.)  Would you be interested in (a PR) adding these features?  I see two options:
* Add more props like `minimizeIcon`, etc.
* Unify into an `icons` prop whose value can be an object like `{minimize: <FontAwesomeIcon...>}`

**Comment by nealus** [comment]
I think the second option would be the best
