### ISSUE TITLE
onDrop callback in addTabWithDragAndDrop doesn't return node ID

### ISSUE THREAD

**Issue by flekmatik** [caplin/FlexLayout#135]
Hey guys, thanks for awesome job on FlexLayout.

In my workflow I need to do modification to node after user drops it on the layout.

Currently I have to search for the dropped node so I can change its config object. When I provide node ID to addTabWithDragAndDrop function I get an error about duplicate IDs.

I think it makes sense for onDrop callback to return ID of newly created/dropped node so I'll provide a pull request. Please tell me if the whole node should be returned instead or it should be solved by some other way.

**Comment by nealus** [comment]
Have you tried the latest version, I think the error when adding a node with addTabWithDragAndDrop is fixed?

**Comment by flekmatik** [comment]
You are correct, thanks. I still think it'd be nice for the callback to return tab identifier but there is easy workaround. Feel free to close this issue & PR.
