### ISSUE TITLE
Add tab without selecting

### ISSUE THREAD

**Issue by edemaine** [caplin/FlexLayout#137]
I'd like to be able to add a new tab to an existing tabset *without* it being selected. As far as I can tell from the code, this isn't currently possible:
* `Model.doAction`, `case Actions.ADD_NODE`, calls `Tabset.drop`.
* `TabSetNode.drop` calls `_setSelected` immediately after `_addChild`:
  ```js
      if (dragNode.getType() === TabNode.TYPE) {
        this._addChild(dragNode, insertPos);
        this._setSelected(insertPos);
  ```

I'm thinking we could add a flag to `ADD_NODE` `Action`s, and an argument to `drop`, for whether to disable this behavior (say, `doNotSelect`).  I'm happy to make a PR implementing this, but I thought it'd be good to check first whether there's a better way to do this.

**Comment by nealus** [comment]
Cannot think of another way

**Comment by edemaine** [comment]
Hmm, in implementing this, I realize that `BorderNode.drop`'s behavior is different: It selects the added tab only if there isn't already a selected tab.
```js
    if (this.getSelected() !== -1) { // already open
      this._setSelected(insertPos);
    }
```

It might be cleaner to change TabSet's behavior to match this.  Then you can always use `Actions.selectTab` if you want to select it... But this would be a breaking change. Which do you prefer? An alternative would be to change BorderNode's behavior to match Tabset, and have them both controlled by `doNotSelect` optional argument...

**Comment by nealus** [comment]
I think using a doNotSelect optional arg in both cases is the safest
