### ISSUE TITLE
Demo: _toAttributeString() issue

### ISSUE THREAD

**Issue by EAzari** [caplin/FlexLayout#142]
I tried to run the [Demo](https://github.com/caplin/FlexLayout/tree/master/examples/demo) but it seems that this part gets error:

```ts
    onTableClick = (node:Node, event:Event) => {
        console.log("tab: \n" + node._toAttributeString());
        console.log("tabset: \n" + node.getParent()!._toAttributeString());
    }
```

The error:
`Property '_toAttributeString' does not exist on type 'Node'.`

I use these imports in App.tsx
```ts
import React from 'react';
import ReactDOM from 'react-dom';

import * as FlexLayout from 'flexlayout-react';
import { Node, TabSetNode, TabNode, DropInfo, BorderNode} from 'flexlayout-react';
import Utils from './Utils';
```
The structure:
```
|_ Modules: react, react-dom, react-scripts, flexlayout-react
|_ public: index.html, light.css, dark.css, popout.html
|_ src: images, layouts, App.tsx, Utils.tsx
| package.json, package-lock.json, tsconfig.json
```

So, how can I solve this error?

Also, there's a no-loop-func error:
`Function declared in a loop contains unsafe references to variable(s) 'i'.`
```ts
        var rows = [];
        for (var i = 0; i < this.props.data.length; i++) {
            var row = this.props.fields.map((field:any) => <td key={field}>{this.props.data[i][field]}</td>);
            rows.push(<tr key={i}>{row}</tr>);
        }
```

**Comment by nealus** [comment]
The _toAttributeString is @internal so should not be accessed externally (the demo is bundled together with flexlayout so this is not an issue there). 

Just comment out those lines (or annotate each line with // @ts-ignore should also work)

**Comment by EAzari** [comment]
Thank you @nealus, so I close this issue then
