### ISSUE TITLE
How to use selfRef with ag-grid ?

### ISSUE THREAD

**Issue by mostafa-raafat** [caplin/FlexLayout#147]
How can i access selfRef and then pass it down to ag-grid component ?

```
factory(node) {
    let component = node.getComponent();
    if (component === "AddCall") {
      return <AddCall />;
    } else if (component === 'CallsList') {
      return <CallsList /> // AG-Grid Component     <============
    }
    else if (component === 'Map') {
      return <Map />;
    }
  }

**Comment by nealus** [comment]
if your factory function is bound to 'this' (or an arrow function is used) then you can just pass this.selfRef as a prop to CallsList
e.g <Layout ref={this.selfRef} factory={this.factory.bind(this)}....
 or  define factory like this:
factory = () => { .... so it's bound to this

**Comment by mostafa-raafat** [comment]
But how can i access selfRef inside <CallsList /> => (AG-Grid) component ?

**Comment by mostafa-raafat** [comment]
here is my app.js
```
factory(node) {
    let component = node.getComponent();
    if (component === "AddCall") {
      return <AddCall />;
    } else if (component === 'CallsList') {
      return <CallsList />
    }
    else if (component === 'Map') {
      return <Map />;
    }
  }

  render() {
    return (
      <FlexLayout.Layout
        ref={this.selfRef}
        model={this.state.model}
        factory={this.factory.bind(this)} />
    );
  }
```
ag-grid.js component 

```


const CallsList = (props) => {
  const [rowData, setRowData] = useState(props.calls);

  useEffect(() => {
    setRowData([...props.calls])
  }, [props.calls])

  return (
    <div
      className="ag-theme-alpine"
      style={{
        height: '100%',
        width: '100%'
      }}
    >
      <AgGridReact
        onGridReady={onGridReady}
        rowData={rowData}
        immutableData={true}
        getRowNodeId={data => data.attributes.id}
        getDocument={() => /* i need to return selfRef here ? */ }    // selfRef -------------->
        pagination={true}
        columnDefs={[{
          headerName: "Id", field: "attributes.id"
        }, {
          headerName: "Location", field: "attributes.location"
        },
        {
          headerName: 'Zoom',
          field: 'value',
          cellRenderer: 'btnCellRenderer',
          colId: 'params',
          width: 180,
        },
        {
          headerName: 'Update',
          field: 'value',
          cellRenderer: 'btnCellUpdate',
          colId: 'params',
          width: 180,
        }]}
        defaultColDef={{
          editable: true,
          enableRowGroup: true,
          enablePivot: true,
          enableValue: true,
          sortable: true,
          resizable: true,
          filter: true,
          flex: 1,
          minWidth: 100,
        }}
        context={{ componentParent: this }}
        frameworkComponents={{
          btnCellRenderer: BtnCellRenderer,
          btnCellUpdate: BtnCellUpdate,
        }}
      >
      </AgGridReact>
    </div>
  )
}

**Comment by nealus** [comment]
I think you want something like:

const CallsList = (props) => { 
...
const selfRef = React.useRef<??>()

<AgGridReact
        ref={selfRef}
        ...
        getDocument={() => return selfRef.current.ownerDocument }

**Comment by mostafa-raafat** [comment]
Cannot read property 'ownerDocument' of null
so right now selfRef.current is undefined, in the Grid component i don't have access to layout.document
do you have any working demo using ag-grid with flex-layout ?

**Comment by nealus** [comment]
actually you may need the ref to be on the div element in the CallsList

**Comment by mostafa-raafat** [comment]
still getting Cannot read property 'ownerDocument' of null

app.js
```
class App extends React.Component {
  constructor(props) {
    super(props);
    this.state = { model: FlexLayout.Model.fromJson(MainLayout) };
  }

  factory(node) {
    let component = node.getComponent();
    if (component === 'CallsList') {
      return <CallsList />
    }
  }

  render() {
    return (
      <FlexLayout.Layout
        ref={this.selfRef}
        model={this.state.model}
        factory={this.factory.bind(this)} />
    );
  }
}
```
AG-Grid.js Component
```
const CallsList = (props) => {
  const selfRef = React.useRef()
  return (
    <div
      className="ag-theme-alpine"
      ref={selfRef}
    >
      <AgGridReact
         .......
        getDocument={() => selfRef.current.ownerDocument }
      >
      </AgGridReact>
    </div>
  )
}

**Comment by nealus** [comment]
ok try like this:

`const CallsList = (props) => {
  const selfRef = React.useRef()

  const [myDocument, setMyDocument] = useState(null);

  useLayoutEffect( () => {
    setMyDocument(selfRef.current.ownerDocument);
  }, []) 

  
  return (
    <div
      className="ag-theme-alpine"
      ref={selfRef}
    >
      <AgGridReact
         .......
        getDocument={() => return myDocument }
      >
      </AgGridReact>
    </div>
  )
}`

to wait for the ref to be available

**Comment by mostafa-raafat** [comment]
Still getting null for myDocument
If you have sometime Could you please take alook to my [repo](https://github.com/mostafa-raafat/flex-layout-agrid)

**Comment by nealus** [comment]
works for me after adding:
    { myDocument && 
      <AgGridReact
      ...
      >
}

ie only render aggrid once you have the document

**Comment by nealus** [comment]
well the document is being passed thru, since you can change the ag-grid headers when popped out, but the zoom button is not working, don't know about that

**Comment by nealus** [comment]
changing 
```
// export default connect(null, mapDispatchToProps)(BtnCellRenderer);
export default BtnCellRenderer;
```
allows the btnClickedHandler to be called from the popout, so it's something to do with the redux connect()

**Comment by mostafa-raafat** [comment]
Thank you so mush
