### ISSUE TITLE
[Discuss] Will jss better than import a css?

### ISSUE THREAD

**Issue by arnoldcui** [caplin/FlexLayout#150]
If use jss,It will be easier to change style at runtime.

**Comment by arnoldcui** [comment]
Is there any test program If I want change the style from css to jss?

**Comment by nealus** [comment]
There are several 'styles in js' solutions each with their own pros and cons, there is not yet a de facto React standard, 
whichever one you choose adds an extra level of complexity to the code with themes and context passing etc.
I think, for now, it's best to leave the styles in simple css, but I'd be happy to hear other peoples opinions.

**Comment by nealus** [comment]
Ref tests, there are currently no automated tests, all testing is manual

**Comment by arnoldcui** [comment]
> There are several 'styles in js' solutions each with their own pros and cons, there is not yet a de facto React standard,
> whichever one you choose adds an extra level of complexity to the code with themes and context passing etc.
> I think, for now, it's best to leave the styles in simple css, but I'd be happy to hear other peoples opinions.

I agree with that. Jss will make program more complex.

What about make classname from string to enum.

In the past experience, if we need to modify the style dynamically. We will let the cm function do this.

String classname has some problem.If flexlayout library change the classname.The user's program will become invalid.
If use enum,It won't happend.

![image](https://user-images.githubusercontent.com/40977489/93407949-fc198c80-f8c5-11ea-89a7-4f935f52a054.png)
![image](https://user-images.githubusercontent.com/40977489/93408000-1d7a7880-f8c6-11ea-8c45-0f3477c5fd92.png)

**Comment by nealus** [comment]
Changing the classnames to enum values makes sense.
