### ISSUE TITLE
A row with border

### ISSUE THREAD

**Issue by Flamingo09** [caplin/FlexLayout#156]
Hey All, I have a specific case, where inside of having a global border component for whole page, I want to have the border for one of the container. Attaching the image of the requirement.
![FlexLayout](https://user-images.githubusercontent.com/54772819/93804418-e6102100-fc63-11ea-9653-47224874ff8a.png)

**Comment by nealus** [comment]
You can use a layout within a layout to have a border for the whole page and then a border for the inner layout.

**Comment by Flamingo09** [comment]
I wanted to have a common config for it. Anyway , thanks. Will do this way.
