### ISSUE TITLE
Creating a Tabset inside a Tab

### ISSUE THREAD

**Issue by maxnathaniel** [caplin/FlexLayout#157]
Hi all,

I am trying to create a new **Tabset** inside an active Tab.

You can refer to the illustration below where **Tabset 2** is inside **Tab 1**. When user moves away from **Tab 1**, the bottom **Tabset 2** should not render since it is stored inside **Tab 1**.

<img src="https://i.ibb.co/YLS5g8N/flex-layout.png" alt="flex-layout" border="0">

**Use Case** 
The active **Tab** has a 1 to many relationship to the Tabs in **Tabset 2**. For instance, the active Tab contains a Parent Report and the tabs inside **Tabset 2** are sub reports.

**What I have tried** 
1. Adding tabs into the border array. However, when I switch to another Tab, the tabs in the border remains. 
2. Adding normal tabs with **DockLocation.BOTTOM**. And this obviously does not work because the bottom positioned tab will remain even when I switch to other tabs.

**Possible solutions**
1. Create a new FlexLayout instance inside the active **Tab**. Is that possible?

Thank you, and looking forward to any suggestions.

**Comment by nealus** [comment]
You can create a new FlexLayout within the first tab for this, the 'sublayout' layout in the demo app shows this, the 'Letters' main tab contains a sublayout with 'AAAA' and 'BBBB' tabs (displayed at the bottom here)
![image](https://user-images.githubusercontent.com/16133809/94109765-6045ce80-fe39-11ea-9910-72f6281a5ab3.png)

**Comment by maxnathaniel** [comment]
Thanks for your reply. 

Yes, I had seen the example that you pasted.

Question is - How do I add/place the new FlexLayout inside the active **Tab** via the exposed APIs?

**Comment by nealus** [comment]
So you would create the sublayout with a top section (without tabbar?) and a bottom section with tabs, the sublayout is simply a react component returned by the factory method for the top level layout.

**Comment by maxnathaniel** [comment]
Oh yes, if I initialize the layout with JSON, then yes, it's straightforward.

However, my initial state is just the **tabset** with a couple of **tabs**. And on click on a button, I want to create the new FlexLayout inside the active **tab**. What I am trying now is grab the active tab ID, and do a updateNodeAttribute. Doesn't look promising.

Otherwise, how do I add the new FlexLayout instance to the active **tab** on the fly?

**Comment by nealus** [comment]
Is the button in the active tab panel  (something like a 'Show Details' button ) or outside the main flexlayout?

**Comment by maxnathaniel** [comment]
The button is within the tab. So every tab would have that button, and on click, it should create the new FlexLayout within the active tab. Basically, that's it.

**Comment by nealus** [comment]
so the React component within the tab hosts a flexlayout component  with a button, the click handler of which will change the flexlayout model (either by the api or by just loading a new json layout)

**Comment by maxnathaniel** [comment]
So essentially, replace the flex layout model json with a new one? In this case, how do I actually render content within the nested flexLayout programmatically?

**Comment by nealus** [comment]
The outer component will have a flexlayout with a model for just the top level tabs.
The outer components flexlayout factory callback should return an inner component for the tabs.
e.g 

factory(node) {
  ...
  return <InnerComponent node={node}/> 
  ...
}

(note: you can pass the model node to the component you are rendering + any other outer props)

The InnerComponent (the actual tab contents) will also host a flexlayout with its own model.

The model json for this component can be dynamically generated: before the button
press it just renders a single header panel, after the button click it will create layout json
for the header plus multiple bottom tabs and create a new model from that json, 
the factory will provide the components for both header and bottom tabs.

Your content is rendered in the factory callback inside the InnerComponent

**Comment by maxnathaniel** [comment]
Yup, the outer components are rendering fine. 

Might be a dumb question - So the button created the new Model json that contains the new FlexLayout instance as an inner component. In the factory callback what's the idiomatic way of passing the **node** instance to the <InnerComponent />? 

Do I create a new **TabNode** instance from the json model? Meaning I do something like this

```
factory(node) {
  const innerModel = node.getConfig().model.layout.children...
  const tabNode = new TabNode(layoutModel, { ...innerModel });

 return <InnerComponent node={tabNode} />;
}
```
And if I do that, would the inner FlexLayout's size/positioning be retained according to the specifications in main layout?

Or is there a better way to achieve that? 

Thank you.

**Comment by nealus** [comment]
The inner component would create its flexlayout model (for the header only) in its constructor/componentdidmount from props (ie generate the json then use the model.fromJson()), this could use the config in the node passed down AND/OR other props.

Pressing the button (in the rendered header) would generate the new layout (with the same header) and create a new model.

The layout of that inner model will not be saved to the outer layout json (when it is serialized to a backing store) unless you update the node.config in some way to save it.

You do not use 'new TabNode' ,the innercomponent just creates the layout in json...

**Comment by maxnathaniel** [comment]
Cool! Got what you are saying. 

I think the last problem that I am facing is this - So the illustration I had pasted in the first post shows that there is a top half and bottom half. The top half renders a component in the main flexlayout model whereas the bottom half renders the inner flexlayout model. 

I realised that while I managed to render the inner flexlayout model, I am unable to render the parent tab. Because in the factory method of the parent flexlayout, I can only **EITHER** return a component at the top level or return an inner component. Is that the expected behaviour?

If that's the case, then my use case will not work.

**Comment by nealus** [comment]
Your inner component can conditionally render just the header or the header and the bottom tabs, so you just need the outer flexlayout to render the inner component

So the innercomponent would create a model like this for just the header

```
{
	"global": {},
	"layout": {
		"type": "row",
		"children": [
			{
				"type": "row",
				"weight": 100,
				"children": [
					{
						"type": "tabset",
						"weight": 50,
						"children": [
							{
								"type": "tab",
								"name": "My Header",
								"component": "header"
							}
						]
					}
				]
			}
		]
	},
	"borders": []
}
```

(where the 'header' component contains a button to show the detail at the bottom)

Then when the button is clicked in the header it would create a new model from json like this (programmatically adding however many tabs to the bottom section)

```
{
	"global": {},
	"layout": {
		"type": "row",
		"children": [
			{
				"type": "row",
				"weight": 100,
				"children": [
					{
						"type": "tabset",
						"weight": 50,
						"children": [
							{
								"type": "tab",
								"name": "My Header",
								"component": "header"
							}
						]
					},
					{
						"type": "tabset",
						"weight": 50,
						"selected": 1,
						"children": [
							{
								"type": "tab",
								"name": "My Detail 1",
								"component": "detail1"
							},
							{
								"type": "tab",
								"name": "My Detail 2",
								"component": "detail2"
							}
						],
						"active": true
					}
				]
			}
		]
	},
	"borders": []
}
```

**Comment by maxnathaniel** [comment]
Thanks for the sample json.

Based on the structure you have shared, I don't see how I can implement it because my layout looks like this. And the button that creates the inner component is found inside the parent "Report" component.

```
{
	"global": {},
	"layout": {
		"type": "row",
		"children": [
            {
                "type": "tabset",
                "weight": 100,
                "children": [
                    {
                        "type": "tab",
                        "weight": 100,
                        "children": [] // the new inner component to inside this tab
                        "name": "Report 1",
                        "component": "Report"
                    },
                    {
                        "type": "tab",
                        "weight": 100,
                        "children": [] // the new inner component to inside this tab
                        "name": "Report 2",
                        "component": "Report"
                    },
                    {
                        "type": "tab",
                        "weight": 100,
                        "children": [] // the new inner component to inside this tab
                        "name": "Report 3",
                        "component": "Report"
                    },
                ]
            }
		]
	},
	"borders": []
}
```

**Comment by maxnathaniel** [comment]
I think I'm on to something.

I passed the inner component's json model into the parent component and create the flexLayout instance in there.
