### ISSUE TITLE
Floating Window Doesn't Update Title when Node Attributes Updated

### ISSUE THREAD

**Issue by allfro** [caplin/FlexLayout#164]
First of all, thank you for creating such a wonderful layout manager. I'm using the floating tab feature and I've come across a bug? When a node is updating its name in the floating window, that name doesn't get reflected in the title of the popup. It only gets reflected in the placeholder tab. Is there something I need to do to get this working?

**Comment by nealus** [comment]
Thanks for reporting that, it is a bug, I'll try to fix in the next update

**Comment by nealus** [comment]
Fixed in 0.5.4

**Comment by allfro** [comment]
Thank you :)
