### ISSUE TITLE
How do I use a tabset within a border?

### ISSUE THREAD

**Issue by allfro** [caplin/FlexLayout#165]
Hello,

I am trying to create a layout where my borders can have tabsets within them. I've tried adding component types `row` and `tabset` into the border definition but it comes out blank. Is there something extra I have to do? Here is what I tried for a model:

```javascript
const tabConfig = {
    global: {
        tabEnableRenderOnDemand: false,
        splitterSize: 2
    },
    borders: [
        {
            type: "border",
            location: "bottom",
            size: 400,
            children: [
                {
                    name: 'Terminals',
                    type: "tabset",
                    weight: 50,
                    selected: 0,
                    children: [
                        {
                            type: "tab",
                            name: "Terminal",
                            component: "terminal",
                            enableFloat: true
                        }
                    ]
                }
            ]
        },
    ],
...
};
```

Basically, to mimic what we see in IntelliJ when we click on the terminal border button:

![image](https://user-images.githubusercontent.com/618125/96456708-dfd27d80-11ec-11eb-88da-3a50f2f249f5.png)

Is this possible?

**Comment by edemaine** [comment]
Yes, it's possible, but not in the way you're trying.  Instead, you need multiple `FlexLayout`s. You want one top-level `FlexLayout` with a bottom border, and then one to implement the tab for each border tab (created by your top-level `factory`). See the "Sublayout" [demo](https://rawgit.com/caplin/FlexLayout/demos/demos/v0.5/demo/index.html). See also #157.

**Comment by allfro** [comment]
Thanks for the response. I guess my follow-up question would be, how do we get a button in the tab strip up top to add additional tabs?

**Comment by nealus** [comment]
You could add a button to the end of the tabbar using the onRenderTab callback

**Comment by allfro** [comment]
Thanks! That works 👍
