### ISSUE TITLE
Bug: Resize listeners get stripped when tab is popped out

### ISSUE THREAD

**Issue by allfro** [caplin/FlexLayout#166]
Window listeners appear to be removed when using the `enableFloat` feature on a tab. I am using `xterm.js` which relies on defining the width and height of a window explicitly in order to render the terminal correctly in the browser window. In order to do that, I've implemented a `ResizeObserver` and attached it to the `div` of my `xterm.js` component. It works great when the terminal is attached to a non-floating tab. However, when I pop the tab out, all resize observers are gone and resizing is no longer detected.

**Comment by nealus** [comment]
I expect this is due to using the main window/document rather than the one for the popout.

From the readme:

"Because popouts are rendering into a different document to the main layout any code in the popped out tab that uses the global document or window objects will not work correctly (for example custom popup menus), they need to instead use the document/window of the popout. To get the document/window of the popout use the following method on one of the elements rendered in the popout (for example a ref or target in an event handler):

    const currentDocument = this.selfRef.current.ownerDocument;
    const currentWindow = currentDocument.defaultView!;

In the above code selfRef is a React ref to the toplevel element in the tab being rendered.
"

**Comment by allfro** [comment]
@nealus I'm not sure I follow. I believe the `ResizeSensor` in `blueprintjs` uses the [`ResizeObserver`](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver) class to observe resize events on the div. I don't see anything referencing window/document other than the ResizeObserver which comes with `window`. Also the `ResizeSensor` is defined as the top-level JSX element in the component. Shouldn't it be cloned over to the popout window?

**Comment by allfro** [comment]
Hi @nealus, it's related to this thread: https://github.com/facebook/react/issues/12355

**Comment by nealus** [comment]
That's almost the same as the code in FloatingWindow.tsx, does that work for your case?

**Comment by allfro** [comment]
Unfortunately, it doesn't. I've tried the code using a small project and it seems like this is a React issue? I'm not sure how to preserve the `ResizeObserver` in the popups. So I think I'll be avoiding it for now until I find a decent solution.

**Comment by nealus** [comment]
have you tried using the window of the popout (rather than the global window object that will point to the parent window) with:
const currentDocument = this.selfRef.current.ownerDocument;
const currentWindow = currentDocument.defaultView!;

where the selfref is any ref to an element rendered in the popout

**Comment by allfro** [comment]
Hi @nealus,

I'm not sure how I'd do that with the following component:

```jsx
export const XTerm = ({visible, initialProcess, onProcess = console.log}) => {
    const ref = useRef();
    const [terminal, setTerminal] = useState(null);
    const [fitter] = useState(new FitAddon());

    useEffect(() => {
        if (visible && terminal === null) {
            const div = ref.current;

            const xterm = new Terminal();
            xterm.loadAddon(fitter);
            xterm.open(div);

            const shellName = process.env[os.platform() === 'win32' ? 'COMSPEC' : 'SHELL'];

            const shell = initialProcess ? initialProcess : pty.spawn(shellName, [], {
                name: 'xterm-color',
                cols: xterm.cols,
                rows: xterm.rows,
                cwd: process.cwd(),
                env: process.env
            });

            onProcess(shell);

            xterm.onData(data => {
                shell.write(data);
            });

            xterm.onResize(({cols, rows}) => {
                if (shell.rows !== rows || shell.cols !== cols) {
                    shell.resize(cols, rows);
                }
            });

            shell.onData(data => {
                xterm.write(data)
            });

            shell.onExit(exitCode => {
                xterm.writeln(`Process exited with exit code: ${exitCode.exitCode} (signal: ${exitCode.signal})`);
            });

            fitter.fit();

            setTerminal(xterm);
        }
    }, [visible]);

    return (
        <ResizeSensor onResize={([{contentRect: {width, height}}]) => {
            if (width !== 0 && height !== 0)
                fitter.fit();
        }}>
            <div ref={ref} style={{height: '100%', width: '100%'}}/>
        </ResizeSensor>
    );
}
```

**Comment by nealus** [comment]
Maybe ResizeSensor does access the global (parent window) document or window

**Comment by nealus** [comment]
or does ResizeSensor use ResizeObserver? which is window.ResizeObserver, so should become currentWindow.ResizeObserver

**Comment by nealus** [comment]
or you could have size state that gets updated in useLayoutEffect using the ref

somethine like this:

`const [size, setSize] = React.useState({w:0, h:0});
const ref = React.useRef(null);

React.useLayoutEffect(() => {
  if (size.w !== ref.current.clientWidth || size.h !== ref.current.clientHeight) {
    fitter.fit();
    setSize({w:ref.current.clientWidth, h: ref.current.clientHeight});
  }
});
`

**Comment by allfro** [comment]
I've moved away from `ResizeSensor` in blueprintjs and opted for just a raw implementation of the `ResizeObserver` instead. That works perfectly, although, it would be nice if we could achieve the popout with an onPopOut/onFloat event handler as well. This way we can specify a different component tree for the popout (like including a toolbar for floating bars vs non-floating).

**Comment by LeoLeoni** [comment]
I had a similar issue in a plotting library that I'm working on and this is what ended up working for me:
```tsx
  const onResize: ResizeHandler = useCallback(
    ({ width, height }) => {
      plotDimensionCallback && plotDimensionCallback(height, width);
    },
    [plotDimensionCallback]
  );
  const plotRef = useRef<HTMLDivElement>();

  const onResizeWindow = useMemo(
    () =>
      debounce(() => {
        const r = plotRef.current.getBoundingClientRect();
        onResize({ width: Math.ceil(r.width), height: Math.ceil(r.height) });
      }, 200),
    [onResize]
  );
  useEffect(() => {
    const currentDocument = plotRef.current?.ownerDocument;
    const currentWindow = currentDocument?.defaultView;

    currentWindow?.addEventListener("resize", onResizeWindow);
    return () => currentWindow?.removeEventListener("resize", onResizeWindow);
  }, [onResizeWindow]);

```
