### ISSUE TITLE
Closing the last tab of a maximized tabset crashes the layout

### ISSUE THREAD

**Issue by Katona** [caplin/FlexLayout#170]
Maximize any of the tabsets then close the tabs on it.

Expected result: when the last tab is closed, then layout should switch back to the 'non-maximized' view showing the original layout without the tabset of which all tabs have been closed.

Actual result: the tabset disappears and the screen turns to white and you are no longer able to interact with the layout.

See this example: https://ph0li.csb.app/

Version: 0.5.4. Older version seems to work fine, like 0.3.0.

**Comment by nealus** [comment]
Thanks for reporting this, I've fixed it in 0.5.5
