### ISSUE TITLE
How does this compare to GoldenLayout?

### ISSUE THREAD

**Issue by philipbjorge** [caplin/FlexLayout#18]
This might be nice to include in the README.

What was the motivation for writing this instead of using GoldenLayout?
What's the feature difference look like?

**Comment by aboyer1013** [comment]
One huge difference for me picking this over GoldenLayout was touch support baked in. In my hunt for a layout manager this was the only one that met my requirements with the flexibility it offered along with touch. I guess I could slap Hammer.js on it, but I'm lazy I guess.
