### ISSUE TITLE
Using this.refs.layout... Where can I find the object 'layout' ?

### ISSUE THREAD

**Issue by yasheena** [caplin/FlexLayout#183]
This is a really great lib! My problem is the documentation: Till now several possibilities are not or not enough described and I cannot find more than the standard example on the net. Especially i cannot found how to access the layout object. When I add the following line of the docs to the example I get the error "TypeError: this.refs.layout is undefined".

<code>this.refs.layout.addTabToTabSet("NAVIGATION", {type:"tab", component:"grid", name:"a grid"});</code>

this.refs is empty but shouldn't be. I tried a lot of things but wasn't successful. Is this a bug or how can I get access to the layout object?

**Comment by nealus** [comment]
The this.refs.layout is an old style reference to the <Layout> element, see: https://reactjs.org/docs/refs-and-the-dom.html

so you need code like:

class MyComponent extends React.Component {
  constructor(props) {
    super(props);
    this.myRef = React.createRef(); // latest way to create a reference to an element
  }
  render() {
    return <Layout ref={this.myRef} ........./>;
  }
}

then use this.myRef.current.addTabToTabSet(....)
