### ISSUE TITLE
BorderTab sizing through displayed component 

### ISSUE THREAD

**Issue by euzu** [caplin/FlexLayout#185]
It is currently possible to give the Border a fixed size. But it should be possible to define the size for the embedded component . If I have tabs in the border, the width should be defined individually for the BorderTab for the component displayed in the current tab, for example. 

Example change in BorderNode.ts
```javascript

 getSize() {
      if (this.resizeBySelectedNode) {
     	return this.getSelectedNode()?._getAttr("size") as number;
      }
      return this._getAttr("size") as number;
    }

```

**Comment by nealus** [comment]
This is now possible with Tab attributes borderWidth and borderHeight (will be in version 0.5.17)
