### ISSUE TITLE
How to control actions in FlexLayout in React

### ISSUE THREAD

**Issue by dacoten** [caplin/FlexLayout#197]
Hi Developer,

I want to ask a question. How can we control the actions in FlexLayout.

When I want to add a new Node and use 

`model.doAction(Actions.addNode({type:"tab", component:"grid", name:"a grid", id:"5"}, "1", DockLocation.CENTER, 0));`

But I cannot use Actions and DockLocation. Actually, I don't know how to call it.
 Please help me

**Comment by edemaine** [comment]
`Actions` and `DockLocation` are within the `flexlayout-react` package, typically imported as `FlexLayout`.  So if you have `import FlexLayout from 'flexlayout-react'` or `FlexLayout = require('flexlayout-react')`, then you should use `FlexLayout.Actions` or `FlexLayout.DockLocation`, just like you use `FlexLayout.Model`.
