### ISSUE TITLE
Custom button on Tab

### ISSUE THREAD

**Issue by daxsorbito** [caplin/FlexLayout#22]
Hi, nice project btw... I would just like to ask if it is possible to add a custom button on the tab? For example  I would like to add a pop-out button before the close button...

Thanks.

**Comment by nealus** [comment]
You can customise the tab rendering in a Layout by implementing a onRenderTab callback property:

Layout.propTypes = {
    model: PropTypes.instanceOf(Model).isRequired,
    factory: PropTypes.func.isRequired,

    onAction: PropTypes.func,

    onRenderTab: PropTypes.func,
    onRenderTabSet: PropTypes.func,

    onModelChange: PropTypes.func
};

This will receive the node and an object of the form: {leading: leadingContent, content: node.getName()} that you can modify.
The leading and content objects are used when rendering the tabbutton:

from this code in the TabButton:

        // allow customization of leading contents (icon) and contents
        const renderState = {leading: leadingContent, content: node.getName()};
        this.props.layout.customizeTab(node, renderState);

so you should be able to return a react component in content (rather than the string: node.getName())

**Comment by daxsorbito** [comment]
thanks for a quick response... I actually found it out that assigning context a react component would do the trick.. but the problem is the click of the button is not firing... do you know how to make this work? any workaround?

**Comment by nealus** [comment]
if you look at the close button in TabButton, it has handlers for onMouseDown 

onCloseMouseDown(event) {
    event.stopPropagation();
}

closeButton = <div className={"flexlayout__tab_button_trailing"}
                   onMouseDown={this.onCloseMouseDown.bind(this)}
                   onClick={this.onClose.bind(this)}
                   onTouchStart={this.onCloseMouseDown.bind(this)}
    />;

I think this is what you need to prevent the tab itself capturing the mouse down for potential dragging

**Comment by daxsorbito** [comment]
Thanks... I was able to make it work.. have to handle the onMouseDown...

**Comment by phuongmillion** [comment]
> Thanks... I was able to make it work.. have to handle the onMouseDown...

could you pls show your your handle code onMouseDown?

**Comment by jugraj** [comment]
Hello, 

I know this was closed a while back, and a long shot, but are you able to post an implementation for this? 

I have a similar use case, where I need to invoke a pop up before the tab is closed. I need to confirm via the popup if the tab should be closed or remain active. 

I.e., the user clicks on the close button, it opens a popup with "Are you sure?" and "Stay" buttons. Clicking on "Are you sure" will close the tab and Stay will basically close the popup.

Any help will be greatly appreciated. 

Thanks,
Jay

**Comment by edemaine** [comment]
Here is an example of such a button (using react-bootstrap, but you could style however you want):

https://github.com/edemaine/comingle/blob/main/client/ConfirmButton.coffee

And an example of how to use in `onRenderTab`:

https://github.com/edemaine/comingle/blob/f7912e541455afb0a66c9beefc3e935b1321dbc0/client/Room.coffee#L381

**Comment by jugraj** [comment]
@edemaine - Thank you so much. It was a bit fiddly but put me in the right direction! 😅 Thanks again 👍🏼

**Comment by jugraj** [comment]
All working barring this solution doesn't trigger `FlexLayout_DeleteTab` action event for some reason. I have tried different ways but to no avail. 

so `model.doAction(FlexLayout.Actions.deleteTab(tabNodeId));` deletes the tab but it doesn't trigger above - which means the logic I need after delete is never run. 

I am sure I am missing something but can't figure it out 🤔

**Comment by edemaine** [comment]
As I recall, actions generally do not trigger events, so you need to call callbacks explicitly when performing actions. (Maybe to prevent infinite loops?) I agree this is weird. Maybe an option could be passed when adding callbacks on whether to also call from actions?
