### ISSUE TITLE
Realtime tab resizing as you drag gutters

### ISSUE THREAD

**Issue by stevewillard** [caplin/FlexLayout#241]
Hi there - great library!

Is there a way to tap into the resize events for resizing to update the tabs in real time as you drag?

**Comment by nealus** [comment]
There is currently no option to resize realtime or allow you to link into the splitter resize,
however I've just tried it by copying this code:

```
let value = 0;
if (outlineDiv) {
    if (node.getOrientation() === Orientation.HORZ) {
        value = outlineDiv.current!.offsetTop;
    } else {
        value = outlineDiv.current!.offsetLeft;
    }
}

if (parentNode instanceof BorderNode) {
    const pos = (parentNode as BorderNode)._calculateSplit(node, value);
    layout.doAction(Actions.adjustBorderSplit((node.getParent() as Node).getId(), pos));
} else {
    const splitSpec = parentNode._calculateSplit(node, value);
    if (splitSpec !== undefined) {
        layout.doAction(Actions.adjustSplit(splitSpec));
    }
}

```
from the splitter.tsx onDragEnd() to the end of the onDragMove() method and that seems to work in the demo.

**Comment by stevewillard** [comment]
This works pretty well for me - great idea! Is there any chance this could maybe become a prop that a user could opt into? I guess the only downside is that this may impact performance?

**Comment by nealus** [comment]
Added prop to 0.5.13 with warning about performance

**Comment by stevewillard** [comment]
Awesome! Thank you so much. 🙌
