### ISSUE TITLE
Is there a way to communicate with two tabs?

### ISSUE THREAD

**Issue by mmasdivins** [caplin/FlexLayout#247]
I would like to know if there is a way we can pass data from one tab to another in a bidirectional way. Something similar to EventHub  that https://golden-layout.com/tutorials/getting-started-react.html had.

**Comment by LoganDark** [comment]
You can expose a [React context](https://reactjs.org/docs/context.html) around the `Layout` component and then use that context for communication. You can use the config of the tabs to tell the components what to do, all components get a `tab` prop that is the TabNode the component is inside.

**Comment by mmasdivins** [comment]
Thanks, right know I did a global event hub where the tabs subscribe and unsubscribe, but I will try your solution.

**Comment by varnguyen** [comment]
Hi,

Can you send some specific examples?

Please

**Comment by greggman** [comment]
The react context docs cover this pretty well

https://reactjs.org/docs/context.html

at the base you do something like

```
<MyContext.Provider value={{ various things }}>
    <FlexLayout.Layout ... />
</MyContext.Provider>
```

inside any component in a Tab you can

```
function SomeComponent() {
   const {various things} = useContext(MyContext);
   ...
}
```

You can pass down state and functions


```
const MyContext = React.createContext();

function App() {
  const [count, setCount] = useState(0);

  return (
  <MyContext.Provider value={{count, setCount}}>
    <FlexLayout.Layout ... />
  </MyContext.Provider>
  );
}
```

```
function SomeComponent() {
   const {count, setCount} = useContext(MyContext);
   return (
      <button onClick={() => setCount(count + 1)}>
         click to inc, current count: {count}
      </button>
   );
}
```

Now if they're are 2 or more `SomeComponent`s in different tabs they'll all be using the same count and if any of them get clicked they'll increment the same state and all update.

https://codesandbox.io/s/flexlayout-context-to-communicate-4k09wb?file=/src/index.js
