### ISSUE TITLE
[Question] Get selected tab

### ISSUE THREAD

**Issue by Pedro-fsa** [caplin/FlexLayout#249]
Hi, 

I've been looking through the docs and haven't been able to solve this problem. I need to save the id of the active (selected) tab to redux state. I can achieve this through the onAction prop, but when you delete the currently selected tab, I have no way of knowing which tab is going to be selected next.

Thank you.

**Comment by nealus** [comment]
On the model object there are various methods (getNodeById, visitNodes etc) that allow you to get/find the tabset then
use getSelected().

**Comment by LoganDark** [comment]
> I need to save the id of the active (selected) tab

`model.getActiveTabset()?.getSelectedNode()?.getId()` returns the selected tab's ID, or `undefined` if nothing is selected (if the user focused an empty tabset, or the model was just created and they haven't clicked anything yet)

**Comment by Pedro-fsa** [comment]
> > I need to save the id of the active (selected) tab
> 
> `model.getActiveTabset()?.getSelectedNode()?.getId()` returns the selected tab's ID, or `undefined` if nothing is selected (if the user focused an empty tabset, or the model was just created and they haven't clicked anything yet)

Thanks, that worked pretty well.
