### ISSUE TITLE
How to delete/close a TabSet?

### ISSUE THREAD

**Issue by balazs-edes-lab49** [caplin/FlexLayout#256]
I'm trying to programmatically delete a TabSet.

`Actions.deleteTab` doesn't do anything (possibly because it's not a tab):
https://github.com/caplin/FlexLayout/blob/d8cac2915e8968a26bf3592ffe70c248c0d9d2dc/src/model/Model.ts#L257

```ts
model.doAction(Actions.deleteTab(tabSet.getId()));
```

Deleting each tab separately closes all the tabSet's content, but the tabset itself is still there.

```ts
tabSet
  .getChildren()
  .map((node) => Actions.deleteTab(node.getId()))
  .forEach((action) => model.doAction(action));
```

I tried updating the parent's attributes too, eg.:

```ts
const parent = tabSet.getParent();
if (isNil(parent)) {
  return;
}
// Logic not exactly the same, but illustrates my point
model.doAction(Actions.updateNodeAttributes(parent.getId(), { children: [] }));
```

But this doesn't do anything either.

Can you advise on how to kill a tabset?

**Comment by ruhullahshah** [comment]
@balazs-edes-lab49 Do you want the tabset to disappear from the layout when all the tabs are closed? If yes, then the global option `tabSetEnableDeleteWhenEmpty` should take effect if you did not set it to `false` in the global config. Please note that you can set it per tabset as well in case you want to turn off the global behavior.

**Comment by balazs-edes-lab49** [comment]
@ruhullahshah Ideally I'd like to close a TabSet, independently from the `tabSetEnableDeleteWhenEmpty` property. Since TabSet has it's own model, I assumed it's possible to delete/close the TabSet itself instead of it's individual children. Is this possible somehow?

**Comment by ruhullahshah** [comment]
@balazs-edes-lab49 I think I get your question now. If I understand you correctly, even if you have a tabset with 3 tabs open, let us say, you still want have the possibility to delete it. I know of no straightforward way to do this. Maybe there is a config option that my eye missed.

**Comment by nealus** [comment]
There is currently no model Action for closing a tabset directly, but I can see it's a valid use case so will
add it to the next update.

**Comment by balazs-edes-lab49** [comment]
This would be awesome guys, yes I'd like to close the TabSet, no matter what's in it.

**Comment by nealus** [comment]
Added v0.5.16 with tabset attribute 'enableClose' for this, or you can use the action deleteTabset.
See the New Features layout in the demo for an example https://rawgit.com/caplin/FlexLayout/demos/demos/v0.5/demo/index.html

**Comment by nealus** [comment]
There should be a view folder, I just tried removing node modules and calling yarn again in the CRA example and I've got the view folder

**Comment by balazs-edes-lab49** [comment]
Could it be that the view folder is not published for some reason? I'm gonna do now a full fresh install, maybe something got stuck on my end.

**Comment by balazs-edes-lab49** [comment]
I'm sorry for the false alarm, there was something stuck on my end. `npm install --force` solved this. Thanks again for the change!
