### ISSUE TITLE
TabSetMinWidth and tabSetMinHeight are invalid

### ISSUE THREAD

**Issue by yuanchangjian** [caplin/FlexLayout#263]
TabSetMinWidth and tabSetMinHeight are invalid, how do I limit the size of tabsets ？

**Comment by nealus** [comment]
`{
	"global": {
        "tabSetMinHeight":100,
        "tabSetMinWidth":100
	},
	"layout": {
           ...
`
should work

**Comment by nealus** [comment]
One thing you could try is intercepting the resize action with the onAction prop of the Layout

```
<Layout onAction={this.onAction} ..


onAction = (action: Action) => {
    if (action.type === Actions.ADJUST_BORDER_SPLIT) {
        if (action.data.pos > 500) {
             action.data.pos = 500;
        }
    }
    return action;
}
```

this would limit the border size to 500
