### ISSUE TITLE
how to make a tab disappear when the style is "visibility: hidden" instead of "display: none"

### ISSUE THREAD

**Issue by yuanchangjian** [caplin/FlexLayout#279]

**Comment by yuanchangjian** [comment]
I use a library in my tab. When the tab is hidden, there will be problems if the tab is set to display: none. Is there any way to change it to visibility: hidden?

**Comment by nealus** [comment]
There is no way to do that currently, but I will look at adding an option it.

**Comment by nealus** [comment]
The problem with adding an option to use visibility instead of display:none is that making a parent element visibility: hidden doesn't prevent a child element from showing thru if it has set visibility: visible.

**Comment by yuanchangjian** [comment]
How to set className in flexlayout__tab?

**Comment by yuanchangjian** [comment]
@nealus I don’t want to hide flexlayout__tab_button, but set flexlayout__tab to visibility: hidden instead of display: none

**Comment by nealus** [comment]
I've added a new global option: enableUseVisibility that switches from display:none to visibility:hidden.

**Comment by yuanchangjian** [comment]
Thank you very much and look forward to improving this project together.
