### ISSUE TITLE
dblclicking tabs generates model changes which prevents tab renaming in edge-cases

### ISSUE THREAD

**Issue by maxleiko** [caplin/FlexLayout#282]
Lets say I want my component hosting the layout, to have the `IJsonModel` as a local state.

```tsx
function MyComp() {
  // local state containing the raw json model
  const [rawModel, setRawModel] = React.useState(DEFAULT_MODEL);

  // memoized model based on the raw model
  const model = React.useMemo(() => Model.fromJson(rawModel), [rawModel]);  

  // model update handler
  const updateModel = (model: FlexLayout.Model) => {
    setRawModel(model.toJson());
  };

  return <FlexLayout.Layout model={model} factory={factory} onModelChange={updateModel} />;
}
```

Every time the model changes (using `onModelChange`), I'll save the `IJsonModel` to this local state (triggering React's re-rendering).

Now, imagine that I want to rename a tab that I have in my layout.  
I double-click the tab, which will trigger a model update, which will trigger the `onModelChange`, which will update the local state, which will trigger a re-rendering of the component, and because the model does not state that I'm currently renaming a specific tab, I lost the renaming feature.

I've made a demo to illustrate just that: https://codesandbox.io/s/focused-ganguly-ucuxs?file=/src/App.tsx

I feel like, the double-click should override the "Select_Tab" action, like, if you double-click to rename, you should first let the rename action happen, and then "Select_Tab" (maybe), this will prevent this specific chain of events to happen.

PS: I've already mention this in https://github.com/caplin/FlexLayout/issues/271, but because it is closed, I don't know if you've seen it.

**Comment by nealus** [comment]
I think the problem is that you are reloading the model from the rawModel each time it changes, you only need to load it initially (the model is mutable and will keep track of the changes).

**Comment by maxleiko** [comment]
Nevermind, you are totally right.

For the sake of completeness, here's the proper way to handle it:

```tsx
const LS_MODEL = "app-model";
const DEFAULT_MODEL: IJsonModel = ...

function loadModelFromLocalStorage(): IJsonModel {
  const rawModel = localStorage.getItem(LS_MODEL);
  let model: IJsonModel;
  if (rawModel) {
    // reload from previous state
    model = JSON.parse(rawModel);
  } else {
    // no previous state: use default model
    model = DEFAULT_MODEL;
  }

  return model;
}

function factory(node: TabNode) {
  // ...
}

const MyComp: React.FC = () => {
  const [rawModel] = React.useState(loadModelFromLocalStorage);
  const model = React.useMemo(() => FlexLayout.Model.fromJson(rawModel), [rawModel]);

  // Called when the layout model changes and updates the local storage with it
  const handleModelChange = React.useCallback((model: Model) => {
    localStorage.setItem(LS_MODEL, JSON.stringify(model.toJson()));
  }, []);

  return (
    <FlexLayout.Layout model={model} factory={factory} onModelChange={handleModelChange} />
  );
}

export default MyComp;
```
