### ISSUE TITLE
buttonFactory prop for customizing buttons.

### ISSUE THREAD

**Issue by SupremeTechnopriest** [caplin/FlexLayout#286]
Hello, 

Im working on a PR to be able to customize full buttons and not just the button icons.  Would you like me to implement a `ButtonNode` model similar to `TabNode` or would an interface be fine?

The way I have it now is:

```ts
export type ButtonType = 'overflow' | 'float' | 'max' | 'min' | 'close' 

export interface IButton {
  name: ButtonType
  icon: React.ReactNode
  hidden?: { node: TabNode, index: number }[]
  props: {
    key: string
    ref: React.MutableRefObject<HTMLButtonElement | null>
    'data-layout-path': string
    title: string
    onClick: (event: React.MouseEvent<HTMLElement, MouseEvent>) => void
    onMouseDown: (event: React.MouseEvent | React.TouchEvent) => void
    onTouchStart: (event: React.MouseEvent | React.TouchEvent) => void
 }
}
```

```ts
buttonFactory?: (button: IButton) => React.ReactNode | undefined;
```

```tsx
const buttonFactory = (button: IButton) => {
  switch(button.name) {
    case 'max':
      return <button {...button.props}>{button.icon}</button>
    default: 
      return undefined
  }
}

<Layout
  buttonFactory={buttonFactory}
  ...
/>
```

I'd want to get this done the way you want it on the first go, so let me know if you would prefer a model over an interface and I can go down that route instead. 

Thanks!

**Comment by nealus** [comment]
The icons can already be changed to contain a react component using the icons prop.

```
export interface IIcons {
    close?: React.ReactNode;
    closeTabset?: React.ReactNode;
    popout?: React.ReactNode;
    maximize?: React.ReactNode;
    restore?: React.ReactNode;
    more?: React.ReactNode;
}
```

Why do you need to replace the buttons?

**Comment by SupremeTechnopriest** [comment]
So there's a few reasons I want this:

1. I want to use my own button.  If you pass a button to the ReactNode, you end up with invalid HTML from the nested `<button>` elements.

![image](https://user-images.githubusercontent.com/2261598/143721730-c2174a16-d243-4d8e-a1ec-fc5ada860395.png)

2. The other reason is I want to be able to incorporate the overflowbutton's count into my button design.  I want to make the number a badge on the button rather than have it inline.  I also would like to be able to style the drop down to match the rest of the menus in my theme. That's why I included the optional hidden tabs parameter.

![image](https://user-images.githubusercontent.com/2261598/143721758-e4313064-c5de-4bdb-9678-ab61d0660e3e.png)

Is there a way that exists currently to style the overflow menu and the overflow count?  I can probably get around the nested button issue by simulating my button with a div, but the main reason was to be able to style the overflow in more detail.

**Comment by nealus** [comment]
I've added a change that extends the icons property to allow it to return functions to create the icons and also added a new callback, onShowOverflowMenu, that allows you to replace the overflow menu with your own.

```
export interface IIcons {
    close?: (React.ReactNode | ((tabNode: TabNode) => React.ReactNode));
    closeTabset?: (React.ReactNode | ((tabSetNode: TabSetNode) => React.ReactNode));
    popout?: (React.ReactNode | ((tabNode: TabNode) => React.ReactNode));
    maximize?: (React.ReactNode | ((tabSetNode: TabSetNode) => React.ReactNode));
    restore?: (React.ReactNode | ((tabSetNode: TabSetNode) => React.ReactNode));
    more?: (React.ReactNode | ((tabSetNode: (TabSetNode | BorderNode), hiddenTabs: { node: TabNode; index: number }[]) => React.ReactNode));
}
```

```
export type ShowOverflowMenuCallback = (
    node: TabSetNode | BorderNode,
    mouseEvent: React.MouseEvent<HTMLElement, MouseEvent>,
    items: { index: number; node: TabNode }[],
    onSelect: (item: { index: number; node: TabNode }) => void,
) => void;
```

Together those should cover your use case.

**Comment by SupremeTechnopriest** [comment]
Nice! I should be able to make due with that.  Is it published to npm or should I install from github master to test it out?

**Comment by nealus** [comment]
use github, there may be a few changes before the next update

**Comment by SupremeTechnopriest** [comment]
Looks great!

![image](https://user-images.githubusercontent.com/2261598/144727982-bda4c610-d003-4ffa-9fdd-3dd4c33bd83e.png)

Thanks!  Will close this now.

**Comment by alexandrzavalii** [comment]
@nealus how can we remove/replace title for the close button?
Its useful for when we want to have different translations.

``` <div data-layout-path="/ts0/tb0/button/close" title="Close" class="flexlayout__tab_button_trailing"> ... </div> ```

**Comment by nealus** [comment]
you can do this with the i18nMapper prop
