### ISSUE TITLE
Accessibility Support - Keyboard Only and Screen Readers

### ISSUE THREAD

**Issue by patorjk** [caplin/FlexLayout#298]
Firstly, this is a pretty cool project and I thank you all for creating it.

I'm curious if you all have any plans to add any accessibility support, specifically for keyboard only use and screen readers? I like the way react-beautiful-dnd handles this, where items can be dragged and dropped using spacebar to select the item and then the arrow keys to move it (and then spacebar again to drop). You can see a demo [here](https://codesandbox.io/s/mmrp44okvj?file=/index.js) and the shortcuts explained [here](https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/sensors/keyboard.md). It's also screen reader friendly and the screen reader explains how to drag and drop when the list is focused.

Assuming you don't have time, are you still open to a PR (I saw you said you were interested [here](https://github.com/caplin/FlexLayout/issues/118#issuecomment-666148482))?

I'm not saying I'd have time to do this (at the moment I don't have much free time), but figured I'd ask in case I get some time in the future or in case someone else wants to take a stab at this.

**Comment by nealus** [comment]
No current plans for accessibility support/keyboard navigation and PR's are welcome.
