### ISSUE TITLE
Question: Custom click handling in Tab

### ISSUE THREAD

**Issue by frozenhaze17** [caplin/FlexLayout#303]
### Describe the bug

Hi, can you help me with adding some custom features in Tab render functions. I'm try to set custom component to _renderValues.leading_ property in onRenderTab function. My code looks like this: 

```
const onRenderTab = (node: TabNode, renderValues: ITabRenderValues) => {
      renderValues.leading = node.isVisible()
        ? <div onClick={() => {myCustomHandle()}}></div>
        : null;
    };
```
    
   I expect, that my myCustomHandle func was called,  but i see only action of selecting tab (Actions.selectTab(node.getId()))

In your code of TabButton view onClick handle call only onAuxMouseClick. 
```
const onAuxMouseClick = (event: React.MouseEvent<HTMLDivElement, MouseEvent>) => {
        if (isAuxMouseEvent(event)) {
            layout.auxMouseClick(node, event);
        }
    };
```
I guess that block to propagate click event for children components.

Is there any way to resolve my problem? 

 

### Steps to Reproduce the Bug or Issue

1. Add custom component with click handle to renderValues in onRenderTab func
2. Click to component

### Expected behavior

Custom click handle of component must be called

### Operating System

macOS

### Browser Type?

Google Chrome

### Browser Version

98.0

### Screenshots or Videos

<img width="529" alt="Снимок экрана 2022-02-28 в 17 31 14" src="https://user-images.githubusercontent.com/52721223/156000627-9f519719-1a44-4638-b74a-d03d788aa71f.png">

**Comment by zastrowm** [comment]
Both `TabButton.onMouseDown` & `TabSet.onMouseDown` are eating click/mouse events.

One possible fix that I could imagine is bailing out if a specific class is present:

```ts
export function isButtonOverride(event: React.MouseEvent<HTMLDivElement, MouseEvent>) {
    const htmlTarget = event.target as HTMLElement;
    return htmlTarget && htmlTarget.closest(".allow-click") != null;
}

...
const onMouseDown = (event: React.MouseEvent<HTMLDivElement, MouseEvent> | React.TouchEvent<HTMLDivElement>) => {
    if (isButtonOverride(event)) {
        return;
    }

    ...
}
```

**Comment by frozenhaze17** [comment]
> zastrowm

Thanks a lot, this trick help to solve my problem!
