### ISSUE TITLE
Layout occupies full screen and cannot see banner or access menu

### ISSUE THREAD

**Issue by GOVYANSONG** [caplin/FlexLayout#304]
### Describe the bug

This may very well be issue with my understanding of flex layout during my first experiment attempt. In our system, at the top of page there is a banner and system menu. When flex layout is shown, it takes over entire page and hide the banner and menu, which is undesirable. This may be caused by flexlayout_layout style. Is there a way to change this behavior? 

thanks

### Steps to Reproduce the Bug or Issue

Check out the screenshot with banner and system menu bar;
After clicked on a menu item, check the flex layout occupying entire page

### Expected behavior

I would expect flex layout is display underneath the existing banner and system menu bar.

### Operating System

Windows

### Browser Type?

Chrome

### Browser Version

V98.0

### Screenshots or Videos

![workspace_screenshot2](https://user-images.githubusercontent.com/36177352/156442629-2ab13b3e-6b2b-4efa-9311-63bcc1627398.png)
![workspace_screenshot](https://user-images.githubusercontent.com/36177352/156442630-b8866df9-210c-40b0-8cde-952902bfb3f0.png)

**Comment by GOVYANSONG** [comment]
FYI in Chrome DevTools, on the root div element of layout with class name "FlexLayout_layout", i was able to modify position to relative to make layout shown underneath the banner and system menu. Height attribute can overriden same way to allow reasonable initial height.

**Comment by GOVYANSONG** [comment]
FYI https://github.com/caplin/FlexLayout/pull/138

**Comment by nealus** [comment]
Yes you can change the flexlayout__layout style, or host the layout in a container element

**Comment by averybross** [comment]
<img width="1512" alt="Screen Shot 2022-09-10 at 11 33 03 AM" src="https://user-images.githubusercontent.com/4257160/189490555-b2bfc53a-1452-40f1-93b8-7115666b69a9.png">

@nealus I am getting the same error..

I have a wrapper with a footer, head, and main inside... 

the wrapper is flex, the main is pos: rel...

What could I be missing?

The layout system is cut off on the bottom... it's like it's not recalculating the positions of everything.. @nealus any clue why?

**Comment by averybross** [comment]
[here](https://rawgit.com/caplin/FlexLayout/demos/demos/v0.7/demo/index.html) you were able to add UI above the FlexLayout... 

I am not able to do the same and I am not sure why...

**Comment by GOVYANSONG** [comment]
Here is code snippet to set up the flexlayout. hopefully it is useful:

<React.Fragment>
        {model &&
        <div style={{position:"relative", height:"90vh"}}>
                <Layout
                    ref={ layoutRef }
                    model={ model }
                    factory={factory} 
                    onRenderTab={onRenderTab}                
                />    
        </div>  
        }
        </React.Fragment>
