### ISSUE TITLE
Not able to drag tabs while a tabset is maximized

### ISSUE THREAD

**Issue by ssvendsen** [caplin/FlexLayout#308]
### Describe the bug

Thank you for a great component. This is maybe more an observation and a question than a bug.

When maximizing a tabset, it is not possible to drag any of the tabs on that tabset, or any tabs that are plazed on borders.

### Steps to Reproduce the Bug or Issue

As an example, go to https://rawgit.com/caplin/FlexLayout/demos/demos/v0.6/demo/index.html
Maximize one of the tabsets. Note that it is not possible to drag any of the tabs on that tabset, or the tab in the left border.

### Expected behavior

I can't find any documentation on whether the behaviour is intended. 
If dragging is deliberately disabled while a tabset is maximized, could that be mentioned in the documentation? 
Is it possible to automatically disable the maximized state (or show a message) if the user tries to drag a tab?

### Operating System

Windows

### Browser Type?

Chrome

### Browser Version

98

### Screenshots or Videos

None

**Comment by nealus** [comment]
Dragging is currently disabled when maximised, but clearly it should be enabled where it makes sense.

I've added a change to enable it.

**Comment by ssvendsen** [comment]
With version 0.6.9 it is possible to drag while maximized. Thank you for the quick response!
