### ISSUE TITLE
How do I get the tabset ID after the move?

### ISSUE THREAD

**Issue by kijitora2021** [caplin/FlexLayout#318]
First of all, thank you so much for publishing this wonderful library.

In onAction, when action.type is FlexLayout_MoveNode, I cannot get the tabset ID after the move.

**■ Movement when tabs are added to another tab set**
If "location" is "center", the destination tabset ID can be get from toNode.

	Action: {
	  data: {
	    "fromNode": "tab_0",
	    "toNode": "tabset_0",	<= Destination tabset ID
	    "location": "center",
 	    "index": 1
	  },
	  type: "FlexLayout_MoveNode"
	}

■ **Movement when a new tab set is created**
If "location" is not "center", the newly added tabset ID cannot be get.

	Action: {
	  data: {
	    "fromNode": "tab_0",
	    "toNode": "tabset_0",	<= Destination tabset ID
	    "location": "right",
 	    "index": -1
	  },
	  type: "FlexLayout_MoveNode"
	}

This is probably because FlexLayout_MoveNode in onAction is called at the start of tab movement.
How do I get the tabset ID after the move is complete?

**Comment by nealus** [comment]
This should work:

model.getNodeById("tab_0").getParent().getId()

https://rawgit.com/caplin/FlexLayout/demos/demos/v0.7/typedoc/classes/Model.html#getNodeById
https://rawgit.com/caplin/FlexLayout/demos/demos/v0.7/typedoc/classes/Node.html#getParent
https://rawgit.com/caplin/FlexLayout/demos/demos/v0.7/typedoc/classes/Node.html#getId

**Comment by kijitora2021** [comment]
nealus, thanks for the advice.

I tried .getParent().getId() on FlexLayout_MoveNode in onAction.
As a result, the original tabset ID returned.
The procedure is as follows.

**Assumption:** "tab_1" and "tab_2" exist on "tabset_0"

1. Drag "tab_2" to the right on "tabset_0".
2. Drop "tab_2".
3. In FlexLayout_MoveNode of onAction, execute `model.getNodeById( action.data.fromNode ).getParent().getId()`

**Result:** "tabset_0" returned.

**Comment by nealus** [comment]
This needs to be done after the action has been performed, you cannot do it in the Layout.onAction callback.
Try in the Layout.onModelChange callback

https://rawgit.com/caplin/FlexLayout/demos/demos/v0.7/typedoc/interfaces/ILayoutProps.html#onModelChange

**Comment by nealus** [comment]
you can also use the Model.setOnCreateTabSet to return the json for the new tabset, then you are in control of the id created

https://rawgit.com/caplin/FlexLayout/demos/demos/v0.7/typedoc/classes/Model.html#setOnCreateTabSet

**Comment by kijitora2021** [comment]
nealus, thanks for the solutions!

Got the results I expected from Layout.onModelChange callback.
Additionally, I could confirm that tabset ID can be controlled from setOnCreateTabSet.
