### ISSUE TITLE
Changing Tabs or rendering all invisible tabs on startup. 

### ISSUE THREAD

**Issue by ChrisLua** [caplin/FlexLayout#33]
Which function can be used to change tabs during runtime? 
The Problem that i face can be seen in this JS fiddle snipped:
https://jsfiddle.net/9x6hecdw/144/
Panel Three is set to be selected on startup. Pannel two is not rendered if not clicked by hand.
hence an access of the elements in panel Two will allways fail.

Is there a way to render all tabs in the layout?

**Comment by nealus** [comment]
I've added the change provided by LimmaPaulus in pull request 'Add option to disable on-demand rendering #25' that should address this. I will build and generate a new npm bundle shortly
