### ISSUE TITLE
Event listener question

### ISSUE THREAD

**Issue by ChrisLua** [caplin/FlexLayout#34]
The Event listener example from the readme doen't work for me.
the line: this.props.node.setEventListener("resize", function () { alert("test"); }.bind(this)); causes
"TypeError: Cannot read property 'setEventListener' of undefined"
so somehow the node element of props seems to be undefined. 
Here is a JS fiddle snipped based on the flex-layout example.
https://jsfiddle.net/9x6hecdw/153/

how do i attach to events properly?

**Comment by nealus** [comment]
try the fiddle like this:
factory(node) {
    var component = node.getComponent();
    node.setEventListener("resize", function (p) {
       alert("resize event");
  }.bind(this));
    if (component === "text") {
        return (<div className="panel">Panel {node.getName()}</div>);
    }
}

You can pass the node to the child component you are creating in the factory method then use code in its constructor/componentDidMount to listen for changes to its size.

this.props.node.setEventListener("resize", function (p) {
   alert("resize event");
}.bind(this));

**Comment by ChrisLua** [comment]
Thank you very much!
