### ISSUE TITLE
Popout button not consistently showing on Google Chrome/Linux

### ISSUE THREAD

**Issue by ItsNoHax** [caplin/FlexLayout#343]
### Describe the bug

It seems the popout button is not properly showing on the latest Google Chrome. (Version 107.0.5304.68 (Official Build) (64-bit))

This was driving me nuts for a while. But I managed to reproduce it on the demo website.
Just need to switch between browsers (I tried Firefox/Chrome only) at: https://rawgit.com/caplin/FlexLayout/demos/demos/v0.7/demo/index.html

### Steps to Reproduce the Bug or Issue

1. Go to https://rawgit.com/caplin/FlexLayout/demos/demos/v0.7/demo/index.html using Google Chrome
2. Observe the popout icon missing
3. Go to https://rawgit.com/caplin/FlexLayout/demos/demos/v0.7/demo/index.html using FireFox
4. Observe the popout icon is there.

### Expected behavior

I would expect it to behave consistently across all browsers.

### Operating System

Linux, Debian 10

### Browser Type?

Google Chrome

### Browser Version

Version 107.0.5304.68 (Official Build) (64-bit)

### Screenshots or Videos

Chrome
![image](https://user-images.githubusercontent.com/4223434/198342972-0f2f3c88-e555-4e61-9782-3860cd75e17e.png)
Firefox
![image](https://user-images.githubusercontent.com/4223434/198343236-c7d4c8ea-c70b-4ee2-93a1-cd249c01e29b.png)

**Comment by ItsNoHax** [comment]
It seems to work fine on MacOS chrome, firefox and safari.

Will test windows tomorrow.

**Comment by nealus** [comment]
flexlayout shows popouts for modern desktop browsers, determined by the following code: 

```
const isIEorEdge = typeof window !== "undefined" && (window.document.documentMode || /Edge\//.test(window.navigator.userAgent));
const isDesktop = typeof window !== "undefined" && window.matchMedia && window.matchMedia("(hover: hover) and (pointer: fine)").matches;
const defaultSupportsPopout: boolean = isDesktop && !isIEorEdge;
```

you can use the prop 'supportsPopout' to force popups to show

**Comment by ItsNoHax** [comment]
Thanks for the response @nealus. I will close the issue as it solves my problem for now.
