### ISSUE TITLE
tabEnableRenderOnDemand - layout not loading

### ISSUE THREAD

**Issue by ChrisLua** [caplin/FlexLayout#35]
I have loaded the current master of FlexLayout and build it with webpack and npm, since the npm release does not contain the latest changes.
Unfortunatly, i'm somehow not able to get the "tabEnableRenderOnDemand" functionality  to work.

if i add "tabEnableRenderOnDemand : false" to the global config, the layout will not be loaded anymore.
but componentDidMount() is still fired.
"tabEnableRenderOnDemand : true" continues to load as usual.

i thought the "tabEnableRenderOnDemand" would cause a rendering of all layout components, which would make them accessable for JS without selecting the tab before.

Do i have to render the components manually? 

JS fiddle (The behaviour on JSfiddle is not equal to what i recieve on my project)
https://jsfiddle.net/9x6hecdw/158/

**Comment by nealus** [comment]
It should work as you expect.

do you get any exceptions etc in the console?

**Comment by ChrisLua** [comment]
You are right.
I finished my "minimal" testset and tried it locally. this time it worked fine, and as expected. 
I was messing around with the resize events in the greater project. They where calling the ressources before the initialization took place.

Sorry for bothering.
