### ISSUE TITLE
Problem with method addTabWithDragAndDropIndirect

### ISSUE THREAD

**Issue by marvit84** [caplin/FlexLayout#36]
Hi,

I'm trying to add a new tab using the method addTabWithDragAndDropIndirect but when the method is called it creates a overlay and the draggable box is behind this layout and is not accessible (I can't drag the box).

At the chrome inspector I can see the z-index has the correct values but the z-index from drag box is ignored by the nav. The only way to make it works is remove manualy the z-index from the created overlay but it's not a real solution.

I don't know the reason why, someone can help me? any idea?

Thanks.

**Comment by nealus** [comment]
The demo app: https://rawgit.com/caplin/FlexLayout/demos/demos/v0.30/demo/index.html
uses addTabWithDragAndDropIndirect when you press the Add button in the top right corner, does that work correctly in your browser?

If so can you compare it to your example in the chrome inspector etc

**Comment by marvit84** [comment]
The demo works correctly in my browser and the values of the components are the same. however for some reason on my app the  z-index of the box is correctly but it doesn't work. I'm not sure if maybe I need to add any property or something that I must keep in mind.

Thanks again.

**Comment by marvit84** [comment]
I found the problem. I was working with the materialui and the drawer component adds a position:relative on its css and it makes the position absolute of drag box has relative to drawer component. I removed this css property from this materialui component and now it works fine!

Thanks a lot.
