### ISSUE TITLE
Build Error: "Unexpected token export" when attempting to use actions

### ISSUE THREAD

**Issue by AubreyF** [caplin/FlexLayout#367]
### Describe the bug

Summary
We're encountering an unusual "Unexpected token 'export'" build error when attempting to import and use actions. This appears to be related to the way this package exposes exports. Many thanks to anyone who has seen this before and/or has suggestions to resolve.

Project details:
- Typescript
- NextJS v12
- WebPack v5
- Build target: es5

Repro:
- https://stackblitz.com/edit/nextjs-flexlayout-build-error-unexpected-token-export

tsconfig.json:
```
{
	"compilerOptions": {
		"target": "es5",
		"lib": ["dom", "dom.iterable", "esnext"],
		"allowJs": true,
		"skipLibCheck": true,
		"strict": false,
		"forceConsistentCasingInFileNames": true,
		"noEmit": true,
		"esModuleInterop": true,
		"module": "esnext",
		"moduleResolution": "node",
		"resolveJsonModule": true,
		"isolatedModules": true,
		"jsx": "preserve",
		"baseUrl": "./src",
		"paths": {
			"@auth/*": ["modules/auth/*"],
			"@gql/*": ["modules/gql/*"],
			"@graph/*": ["modules/graph/*"],
			"@project/*": ["modules/project/*"],
			"@asset/*": ["modules/projectAsset/*"],
			"@common/*": ["modules/_common/*"],
			"@modules/*": ["modules/*"]
		},
		"downlevelIteration": true,
		"incremental": true
	},
	"include": [
		"next-env.d.ts",
		"**/*.ts",
		"**/*.tsx",
		"scripts/stripeUpdate/index.js"
	],
	"exclude": ["node_modules", "cypress"]
}
```

Sample code:

```ts
import { Actions as FlexLayoutActions } from "flexlayout-react";
...
flexLayoutModelVar().instance?.doAction(
  FlexLayoutActions.selectTab("import")
);
```

Build error we're seeing:
<img width="764" alt="2023-01-26 Google Chrome localhost3000p6608d7e9ebcd497ab6b3401cd6215b46 DQz7Zyqr@2x" src="https://user-images.githubusercontent.com/2789037/215013060-ec73e0ac-46c8-493e-bb27-60d845478b7f.png">

### Your Example Website or App

https://stackblitz.com/edit/nextjs-flexlayout-build-error-unexpected-token-export

### Steps to Reproduce the Bug or Issue

1. Run code
2. See build error

### Expected behavior

Code should not error on build

### Operating System

macOS

### Browser Type?

Chrome

### Browser Version

all

### Screenshots or Videos

<img width="764" alt="2023-01-26 Google Chrome localhost3000p6608d7e9ebcd497ab6b3401cd6215b46 DQz7Zyqr@2x" src="https://user-images.githubusercontent.com/2789037/215013873-d5c78993-1b76-46f7-a0cd-43ae67066351.png">

**Comment by Cacaci** [comment]
Any update or feedback for this issue?

**Comment by ranmocy** [comment]
I think it's the issue in tsconfig2.json. I created PR #378 trying to fix this issue.
Basically I think the generated commonjs code should not contain `export` keyword at all, which is for ESM modules.

**Comment by AubreyF** [comment]
@ranmocy Thanks! I just confirmed that your fix resolves this issue in our production NextJS codebase ✔
