### ISSUE TITLE
crypto.randomUUID is not supported for http

### ISSUE THREAD

**Issue by RabbitShare** [caplin/FlexLayout#379]
### Describe the bug

After Pull Request [#345 ](https://github.com/caplin/FlexLayout/pull/345) there was an error TypeError: crypto.randomUUID is not a function on http sites

### Steps to Reproduce the Bug or Issue

open on any website running on http

### Expected behavior

As user i expected support for http

### Operating System

Linux

### Browser Type?

Chrome

### Browser Version

107

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/49274725/222346439-3f4de952-9c2c-4b25-9328-f038545dbd55.png)

**Comment by nealus** [comment]
thanks for reporting that, I've made a change to the uuid generation in v0.7.7 to fix it
