### ISSUE TITLE
Should addTabToActiveTabSet be public?

### ISSUE THREAD

**Issue by bretcope** [caplin/FlexLayout#43]
I noticed that `Layout.addTabToActiveTabSet(json)` is listed as part of the public API in the README, but [in the code](https://github.com/caplin/FlexLayout/blob/master/src/view/Layout.tsx#L282) it's marked as `@hidden @internal`, and the method doesn't show up in TypeScript. I could imagine the hidden/internal being a copy/paste error, so I just wanted to clarify. Thanks.

**Comment by nealus** [comment]
Yes you are right it should be public, I've made the change, thanks.
