### ISSUE TITLE
Access ref of children component defined in the factory method.

### ISSUE THREAD

**Issue by ddelpiano** [caplin/FlexLayout#45]
As per title, I would like to access the children component defined in the factory method as below

```
factory(node) {
        var component = node.getComponent();
        if (component === "text") {
            return (<div className="panel">Panel {node.getName()}</div>);
        } else if (component === "canvas") {
            return (<div className="panel" id="sim">
                    <Canvas
                        id="CanvasContainer"
                        name={"Canvas"}
                        ref="Canvas" />
                </div>)
        }
    };
```

For instance, I would like to have access to the ref defined within the canvas component called Canvas.
I already tried to define a ref in the FlexLayout component and look for nested refs inside this but that this array was empty.
(For instance, this.refs.layoutRef.refs.Canvas did not exist, this.refs.layoutRef.refs is empty).

```
<FlexLayout.Layout
                    ref="layoutRef"
                    model={this.state.model}
                    factory={this.factory.bind(this)}/>
```

Thanks in advance for the help.

**Comment by nealus** [comment]
Hi Dario, using a ref like this worked for me:

class Main extends React.Component {

    constructor(props) {
    	super(props);
      this.state = {model: FlexLayout.Model.fromJson(json)};
      this.myRef = React.createRef();
    }

		onClick() {
      this.myRef.current.innerText = "here";
    }

    factory(node) {
        var component = node.getComponent();
        if (component === "text") {
            return (<div ref={this.myRef} className="panel"
            onClick={()=>this.onClick()}>Panel {node.getName()}</div>);
        }
    }

    render() {
        return (
            <FlexLayout.Layout
                model={this.state.model}
                factory={this.factory.bind(this)}/>
        );
    }
}

ReactDOM.render(<Main/>, document.getElementById("container"));

**Comment by ddelpiano** [comment]
Thanks @nealus , I arrived to a very similar solution just yesterday looking for other projects on github that used this library :-).
