### ISSUE TITLE
Help with the moveNode Action

### ISSUE THREAD

**Issue by ddelpiano** [caplin/FlexLayout#46]
Hello all,

Just wondering if someone can help me with this method since the example provided in the README is clear but not totally comprehensive of all the parameter required to make this works.
Quick introduction, I am adding a custom icon to allow me to minimize my tabset to one of the two bars I defined in my layout, in order to do this I am hardcoding the id in the json structure for 2 bars defined in there using 1 and 2 for these ids.
Then using the onRenderTabSet prop I am trying to add a div that onClick will execute the action moveNode for the node itself.
Before these changes my layout worked fine, I can even see the icon, the problem is that I am a bit puzzled in the use of the action method moveNode since I do not know how to define the DropLocation and what the last index means, whether for the fromNodeId I rely on the call node.getId() to get the current node and for toNodeId I am relying on the value hardcoded in my json since I need to know the id of my 2 bars.
Thanks in advance for any help (fyi, I already tried to dig in the examples and in all the github projects using this library to see if someone used already this method but no luck).

my json model:
```
var json = {
    global: { tabEnableClose: true },
    borders: [
        {
            "type": "border",
            "location": "bottom",
            "size": 100,
            "id": 1,
            "children": [
                {
                    "type": "tab",
                    "name": "four",
                    "component": "text"
                }
            ]
        },
        {
            "type": "border",
            "location": "left",
            "size": 100,
            "id": 2,
            "children": []
        }
    ],
    layout: {
        "type": "row",
        "weight": 100,
        "children": [
            {
                "type": "tabset",
                "weight": 70,
                "selected": 0,
                "height": 800,
                "children": [
                    {
                        "type": "tab",
                        "name": "Canvas",
                        "component": "canvas"
                    }
                ]
            },
            {
                "type": "row",
                "weight": 30,
                "selected": 0,
                "children": [
                    {
                        "type": "tabset",
                        "weight": 50,
                        "name": "Two",
                        "height": 400,
                        "children": [
                            {
                                "type": "tab",
                                "name": "Term Info",
                                "component": "terminfo"
                            }
                        ]
                    },
                    {
                        "type": "tabset",
                        "weight": 50,
                        "name": "Three",
                        "height": 400,
                        "children": [
                            {
                                "type": "tab",
                                "name": "Stack Widget",
                                "component": "stackwidget"
                            }
                        ]
                    }
                ]
            }
        ]
    }
};
```

onRenderTabSet:
```
var onRenderTabSet = function (node:(TabSetNode), renderValues:any) {
            renderValues.headerContent = "-- " + renderValues.headerContent + " --";
            renderValues.buttons.push(<div className="fa fa-window-minimize" onClick={this.model.doAction(FlexLayout.Actions.moveNode(node.getId(), 1, 0, 0))}/>);
        };
```

Factory method:
```
factory(node) {
        var component = node.getComponent();
        if (component === "text") {
            return (<div className="">Panel {node.getName()}</div>);
        } else if (component === "canvas") {
            return (<Canvas
                id="CanvasContainer"
                name={"Canvas"}
                ref={ref => this.canvasReference = ref} />)
        } else if (component === "terminfo") {
            return (<VFBTermInfoWidget
                termInfoHandler={this.termInfoHandler}
                ref={ref => this.termInfoReference = ref}
                showButtonBar={true}
                order={['Name',
                        'Alternative Names',
                        'Query For',
                        'Depicts',
                        'Thumbnail',
                        'Relationship',
                        'Description',
                        'References',
                        'Aligned To',
                        'Download']} />)
        } else if (component === "stackwidget") {
            return (<StackWidget
                ref={ref => this.stackWidgetReference = ref}
                canvasRef={this.canvasReference}
                stackViewerHandler={this.stackViewerHandler} />)
        }
    };
```

FlexLayout rendered:
```
<FlexLayout.Layout
                                model={this.model}
                                factory={this.factory.bind(this)}
                                onRenderTabSet={onRenderTabSet}/>
```

**Comment by nealus** [comment]
Try this:

    var json = {
        global: {tabEnableClose:false},
        borders:[
            {
                "type": "border",
                "location":"bottom",
                "size": 100,
                "children": [
                    {
                        "type": "tab",
                        "name": "four",
                        "component": "text"
                    }
                ]
            },
            {
                "type": "border",

                "location":"left",
                "size": 100,
                "children": []
            }
        ],
        layout: {
            "type": "row",
            "weight": 100,
            "children": [
                {
                    "type": "tabset",
                    "weight": 50,
                    "selected": 0,
                    "children": [
                        {
                            "type": "tab",
                            "name": "One",
                            "component": "text"
                        }
                    ]
                },
                {
                    "type": "tabset",
                    "weight": 50,
                    "selected": 0,
                    "children": [
                        {
                            "type": "tab",
                            "name": "Two",
                            "component": "text"
                        },
                        {
                            "type": "tab",
                            "name": "Three",
                            "component": "text"
                        }
                    ]
                }
            ]
        }
    };

    const divStyle = {
        color: "red",
    };

    class Main extends React.Component {

        constructor(props) {
            super(props);
            this.state = {model: FlexLayout.Model.fromJson(json)};

            this.model = FlexLayout.Model.fromJson(json)
            this.onRenderTabSet = undefined;
        }

        factory(node) {
            var component = node.getComponent();
            if (component === "text") {
                return (<div className="panel">Panel {node.getName()}</div>);
            }
        }

        onMinimize(tabSetNode) {
           this.model.doAction(FlexLayout.Actions.moveNode(tabSetNode.getSelectedNode().getId(), "border_left", FlexLayout.DockLocation.CENTER, 0));
        }

        render() {

            var key = 0;
            this.onRenderTabSet = function (tabSetNode:(TabSetNode), renderValues:any) {
                if (tabSetNode._attributes.type !== "border") {
                    renderValues.buttons.push(<div style={divStyle} key={key} className="fa fa-window-minimize"
                                                   onClick={this.onMinimize.bind(this, tabSetNode)}></div>);
                }
            }.bind(this);

                return (
                    <FlexLayout.Layout
                        model={this.model}
                        factory={this.factory.bind(this)}
                        onRenderTabSet={this.onRenderTabSet} />
                );
            }
        }

        ReactDOM.render(<Main/>, document.getElementById("container"));


the node is a tabsetnode so you need to get the tabSetNode.getSelectedNode().getId(),
