### ISSUE TITLE
Deleting node doesn't delete it from the idMap.

### ISSUE THREAD

**Issue by neb42** [caplin/FlexLayout#5]
https://github.com/caplin/FlexLayout/blob/e5ad792be4108eda10a38da662a4841e65b7506d/src/model/Model.js#L106

If I delete a tab it stays within the idMap on the model. If I try to open another tab with the same id it will error.

Solution : `delete this._idMap[action.node]`

**Comment by nealatcaplin** [comment]
Thanks Ben, I've applied your fix

**Comment by nealatcaplin** [comment]
fixed #5
