### ISSUE TITLE
className attribute of TabNode does not work

### ISSUE THREAD

**Issue by Kafkalasch** [caplin/FlexLayout#57]
Hi,

first of all, thanks for this great library.

I stumbled upon an issue with the className attribute that can be defined on TabNodes.
It does not work. All Tabs always have only the default "flexlayout__tab" className regardless of the className property.

I looked at the source code and could not find any reference to the TabNode.getClassName() method.

I supposethis issue could be easily fixed in the Tab.render() method by just appending the TabNodes className:

I.e. changing the this code
```
return <div className={cm("flexlayout__tab")}
                    ...
        </div>;
```
to this
```
return <div className={cm("flexlayout__tab") + " " + node.getClassName()}
                    ...
        </div>;
```

**Comment by nealus** [comment]
Hi, thanks for the feedback.

The Tab className attribute is applied to the TabButton rather than the content area of the tab, clearly the name does not make that clear. I will look at adding a separate classname attribute for the content areas in the next update.

**Comment by Kafkalasch** [comment]
ok, I see. Thanks for that!

**Comment by senro** [comment]
HI,  v0.7.6 tab ‘s className still did not work
