### ISSUE TITLE
Bug: code tslint error

### ISSUE THREAD

**Issue by arnoldcui** [caplin/FlexLayout#65]
![image](https://user-images.githubusercontent.com/40977489/56857059-2601a480-699b-11e9-9c8c-845c69d39b8e.png)
![image](https://user-images.githubusercontent.com/40977489/56857061-31ed6680-699b-11e9-9bcc-c6cb038d75cb.png)
![image](https://user-images.githubusercontent.com/40977489/56857077-682ae600-699b-11e9-9ab4-f3d25fe79623.png)
The second parameter of startDrag should be 
```
((pos: { clientX: number, clientY: number }) => boolean) | undefined
```

but give an 

```
(event: React.FormEvent<Element>)=>boolean
```

**Comment by nealus** [comment]
Hi Arnold, thanks for finding that, can you submit a pull request please.

**Comment by arnoldcui** [comment]
> Hi Arnold, thanks for finding that, can you submit a pull request please.

That would be a big change.
Here the pull request #68
